[project]
authors = ["McCoy Becker <mccoybecker@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "patches"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
format = "mojo format ."

[dependencies]
max-pipelines = ">=25.4.0.dev2025050919,<26"
